apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: sabinolabs
      context: ../dotnet-microservice
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
